src/Entity/Bill.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BillRepository")
 * @UniqueEntity("bill_number")
 */
class Bill
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bill_number;

    /**
     * @ORM\Column(type="float")
     */
    private $price_tva;

    /**
     * @ORM\Column(type="float")
     */
    private $price_ttc;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="float")
     */
    private $total_price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Reservation", inversedBy="bills")
     */
    private $Reservation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBilleNumber(): ?string
    {
        return $this->bill_number;
    }

    public function setBillNumber(string $bill_number): self
    {
        $this->bill_number = $bill_number;

        return $this;
    }

    public function getPriceTva(): ?float
    {
        return $this->price_tva;
    }

    public function setPriceTva(float $price_tva): self
    {
        $this->price_tva = $price_tva;

        return $this;
    }

    public function getPriceTtc(): ?float
    {
        return $this->price_ttc;
    }

    public function setPriceTtc(float $price_ttc): self
    {
        $this->price_ttc = $price_ttc;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(float $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->Reservation;
    }

    public function setReservation(?Reservation $Reservation): self
    {
        $this->Reservation = $Reservation;

        return $this;
    }
}

src/Entity/Discount.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DiscountRepository")
 * @UniqueEntity("name")
 */
class Discount
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $discount_value;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CommandDetails", mappedBy="discount")
     */
    private $command_details;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /*public function __toString()
    {
        return $this->discount_value;
    }*/

    public function __construct()
    {
        $this->command_details = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getDiscountValue(): ?string
    {
        return $this->discount_value;
    }

    public function setDiscountValue(float $discount_value): self
    {
        $this->discount_value = $discount_value;

        return $this;
    }

    /**
     * @return Collection|CommandDetails[]
     */
    public function getCommandDetails(): Collection
    {
        return $this->command_details;
    }

    public function addCommandDetail(CommandDetails $commandDetail): self
    {
        if (!$this->command_details->contains($commandDetail)) {
            $this->command_details[] = $commandDetail;
            $commandDetail->setDiscount($this);
        }

        return $this;
    }

    public function removeCommandDetail(CommandDetails $commandDetail): self
    {
        if ($this->command_details->contains($commandDetail)) {
            $this->command_details->removeElement($commandDetail);
            // set the owning side to null (unless already changed)
            if ($commandDetail->getDiscount() === $this) {
                $commandDetail->setDiscount(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


}

src/Entity/Spot.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpotRepository")
 * @UniqueEntity("name")
 */
class Spot
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="spots")
     */
    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $lastName;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $firstName;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $address;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $newsletter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      min = 10,
     *      max = 12,
     *      minMessage = "Your phone number must be at least {{ limit }} characters long",
     *      maxMessage = "Your phone number cannot be longer than {{ limit }} characters"
     * )
     */
    private $phone;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @ORM\OneToMany(targetEntity="Slider", mappedBy="user")
     */
    private $sliders;

    /**
     * @ORM\Column(name="createdAt", type="datetime", nullable=true)
     */
    protected $createdAt;

    /**
     * @ORM\Column(name="editAt", type="datetime", nullable=true)
     */
    protected $editAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="user")
     */
    private $Reservation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Faq", mappedBy="User")
     */
    private $faqs;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function autoUpdateDate() {
        $this->editAt = new \DateTime();
    }

    public function __construct()
    {
        parent::__construct();
        $this->createdAt = new \DateTime();
        $this->editAt = new \DateTime();
        $this->Reservation = new ArrayCollection();
        $this->faqs = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getNewsletter() {
        return $this->newsletter;
    }

    /**
     * @param mixed $newsletter
     */
    public function setNewsletter($newsletter) {
        $this->newsletter = $newsletter;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     */
    public function setAddress($address): void
    {
        $this->address = $address;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }


    /**
     * @return mixed
     */
    public function getSliders()
    {
        return $this->sliders;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservation(): Collection
    {
        return $this->Reservation;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->Reservation->contains($reservation)) {
            $this->Reservation[] = $reservation;
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->Reservation->contains($reservation)) {
            $this->Reservation->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Faq[]
     */
    public function getFaqs(): Collection
    {
        return $this->faqs;
    }

    public function addFaq(Faq $faq): self
    {
        if (!$this->faqs->contains($faq)) {
            $this->faqs[] = $faq;
            $faq->setUser($this);
        }

        return $this;
    }

    public function removeFaq(Faq $faq): self
    {
        if ($this->faqs->contains($faq)) {
            $this->faqs->removeElement($faq);
            // set the owning side to null (unless already changed)
            if ($faq->getUser() === $this) {
                $faq->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function setEmail($email)
    {
        $this->setUsername($email);
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getEditAt()
    {
        return $this->editAt;
    }

    /**
     * @param mixed $editAt
     * @return User
     */
    public function setEditAt($editAt)
    {
        $this->editAt = $editAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return User
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }


}

templates/bundles/FOSUserBundle/Profile/edit.html.twig
{% extends "base.html.twig" %}

{% block fos_user_content %}
{% include "@FOSUser/Profile/edit_content.html.twig" %}
{% endblock fos_user_content %}

templates/bundles/FOSUserBundle/Profile/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="container">
    <h1 class="col-12 text-center" style="color: #0A5524;">Modifier mes informations</h1>
    {{ form_start(form, { 'action': path('fos_user_profile_edit'), 'attr': { 'class': 'fos_user_profile_edit' } }) }}
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6 form-group">
                {# prénom #}
                {{ form_label(form.firstName, 'Prénom') }}
                {{ form_widget(form.firstName, {'attr': {'class': 'form-control', 'placeholder':'Votre prénom'}}) }}
                {{ form_errors(form.firstName) }}
            </div>
            <div class="col-sm-6 form-group">
                {# Nom #}
                {{ form_label(form.lastName, 'Nom') }}
                {{ form_widget(form.lastName, {'attr': {'class': 'form-control', 'placeholder':'Votre nom'}}) }}
                {{ form_errors(form.lastName) }}
            </div>

            <div class="col-sm-12 form-group">
                {# Adresse #}
                {{ form_label(form.address, 'Adresse') }}
                {{ form_widget(form.address, {'attr': {'class': 'form-control', 'placeholder':'Votre adresse'}}) }}
                {{ form_errors(form.address) }}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4 form-group">
                {# Ville #}
                {{ form_label(form.city, 'Ville') }}
                {{ form_widget(form.city, {'attr': {'class': 'form-control', 'placeholder':'Votre ville'}}) }}
                {{ form_errors(form.city) }}
            </div>
            <div class="col-sm-4 form-group">
                {# Pays #}
                {{ form_label(form.country, 'Pays') }}
                {{ form_widget(form.country, {'attr': {'class': 'form-control', 'placeholder':'Pays'}}) }}
                {{ form_errors(form.country) }}
            </div>
            <div class="col-sm-4 form-group">
                {# Code postal #}
                {{ form_label(form.postal_code, 'Code Postal') }}
                {{ form_widget(form.postal_code, {'attr': {'class': 'form-control', 'placeholder':'Code postal'}}) }}
                {{ form_errors(form.postal_code) }}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4 form-group">
                {# Téléphone #}
                {{ form_label(form.phone, 'Téléphone') }}
                {{ form_widget(form.phone, {'attr': {'class': 'form-control', 'placeholder':'Votre téléphone'}}) }}
                {{ form_errors(form.phone) }}
            </div>
            <div class="col-sm-4 form-group">
                {# Email #}
                {{ form_label(form.email, 'Email') }}
                {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder':'Votre adresse mail'}}) }}
                {{ form_errors(form.email) }}
            </div>
            <div class="col-sm-4 form-group">
                {# Date de naissance #}
                {{ form_label(form.birthdate, 'Date de naissance') }}
                {{ form_widget(form.birthdate) }}
                {{ form_errors(form.birthdate) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 form-group">
                {# Mot de passe 1 #}
                {{ form_label(form.current_password, 'Mot de passe actuel') }}
                {{ form_widget(form.current_password, { 'attr': {'class': 'form-control', 'placeholder':'Tapez votre mot de passe'} }) }}
                {{ form_errors(form.current_password) }}
            </div>
            <div class="col-sm-6 form-group">
                {# Mot de passe 2 #}
                {{ form_label(form.username, 'Email') }}
                {{ form_widget(form.username, { 'attr': {'class': 'form-control'} }) }}
                {{ form_errors(form.username) }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 form-group">
            {{ form_widget(form.newsletter, { 'attr': {'class': 'ml-0 position-static'} }) }}
        </div>
        <div class="col-sm-6 form-group">
            <input class="btn btn-success" type="submit" value="{{ 'profile.edit.submit'|trans }}" />
        </div>
    </div>


    {{ form_end(form) }}
</div>

templates/bundles/FOSUserBundle/Profile/show.html.twig
{% extends "base.html.twig" %}

{% block fos_user_content %}
{% include "@FOSUser/Profile/show_content.html.twig" %}
{% endblock fos_user_content %}

templates/bundles/FOSUserBundle/Profile/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <div class="jumbotron">
                <h4>Mes réservations</h4>
                <p class="lead">Ici vous trouverez vos réservations.<br> Attention, toute anulation est irréversible.
                </p>
                <hr class="my-4">
                {% for resa in user.reservation %}
                    <div class="row">
                        <div class="col-md-5">
                            <p class="mt-2">
                                {{ resa.commandDetails.categoryHasSeason.name }}
                            </p>
                            <p>Date de début : {{ resa.reservationStart|date('d/m/Y') }}</p>
                            <p>Date de fin : {{ resa.reservationEnd |date('d/m/Y') }}</p>
                            <p>Option(s) :{{ resa.commandDetails.CommandDetailsHasOption.Options.name }}
                                :{{ resa.commandDetails.CommandDetailsHasOption.price }}€</p>
                            <h5>Prix total : {{ resa.totalPrice }} €</h5>
                        </div>
                        <div class="col-md-3 offset-md-4">
                            <img src="{{ asset('assets/img/slider/' ~ resa.commandDetails.categoryHasSeason.category.media) }}"
                                 alt="emplacement" class="img-fluid mt-2">
                        </div>
                    </div>
                    <a class="btn btn-success" href="#" role="button">Télécharger le PDF</a>
                    {% if resa.isCancelled == false %}
                        <a class="btn btn-danger" href="{{ path ('resa.annulation', {id: resa.id}) }}" role="button">Annuler
                            la réservation</a>
                    {% else %}
                        <button class="btn btn-secondary" href="#">Réservation annulée</button>
                    {% endif %}
                    <hr>
                {% endfor %}
            </div>
        </div>


        <div class="offset-md-1 col-md-3">
            <div class="jumbotron">
                <h4>Mes infos</h4>
                <hr class="my-4">
                <p><strong>Email:</strong> {{ user.email }}</p>
                <hr class="my-4">
                <p><strong>Téléphone:</strong> {{ user.phone }}</p>
                <p><strong>Date de naissance:</strong> {{ user.birthdate | date("d/m/Y") }}</p>
                <hr class="my-4">
                <p><strong>Adresse:</strong> {{ user.address }}</p>
                <p>{{ user.postalCode }} {{ user.city }}</p>
                <p>{{ user.country }}</p>

                <a class="btn btn-success" href="{{ path ('fos_user_profile_edit') }}" role="button">
                    Modifier profil
                </a>
                <a class="btn btn-secondary mt-2 mb-2" href="{{ path ('fos_user_change_password') }}" role="button">
                    Changer mon mot de passe
                </a>
                <a class="btn btn-danger btn-sm" href="{{ path('fos_user_security_logout') }}">
                    {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
                </a>
            </div>
        </div>

    </div>
</div>